### ISSUE TITLE
Badge is displayed several times per game on wishlist

### ISSUE THREAD

**Issue by Deuchnord** [tryton-vanmeer/ProtonDB-for-Steam#37] opened 2022-08-21 09:53 UTC
## Expected Behaviour:
On wishlist, the badge should be displayed only once per game.

## Actual Behaviour:
The badge is displayed several times (generally twice or three times).

![Issue screenshot](https://user-images.githubusercontent.com/7600265/185785490-6ad9b260-439f-46d9-8745-1e1aa1f70254.png)

## Steps to Reproduce:
1. Open your wishlist
2. Contemplate the badges

## Details
Browser:
* [x] Firefox
* [ ] Chrome

Browser Version: **103.0.2**

Addon Version: **1.8.1**

**Comment by RunningDroid** [comment] 2022-12-12 00:28
Refreshing the page can get rid of the extra badges, but they start coming back if you scroll down the page:
![Screenshot 2022-12-11 at 19-06-55 RunningDroid's wishlist](https://user-images.githubusercontent.com/486393/206938353-e21b8039-262a-4928-9ab5-10d53ffa7ec6.png)


Browser: Firefox 107.0.1

Addon Version: 1.8.1

**Comment by shigutso** [comment] 2022-12-27 09:21
Same issue here.
Firefox 108.0.1
Addon 1.8.1

**Comment by Rayquaza01** [comment] 2022-12-29 00:19
This occurs when the script takes more than 1 second to add a badge. The script tries to load badges every second, skipping over games it has already added a badge to. If the page is loading slowly, it adds multiple (because it retries before it finished processing the first time). I'm not entirely sure why, but this can be fixed by adjusting `ProtonDB.request_rating()` to use a promise instead of a callback, and changing `Wishlist.load_ratings()` to be async, and awaiting the ProtonDB request.

Here's a video demo reproducing it with the Firefox devtools throttling: https://www.youtube.com/watch?v=NoZkZqIUAzw

And here's the branch that fixes it by changing to to a promise: https://github.com/Rayquaza01/ProtonDB-for-Steam/tree/promise

**Comment by tryton-vanmeer** [comment] 2023-11-06 00:24
Fixed in 404fe3d407c0aa0ff1f2b8eb7956ae84349c3233

**Closed by tryton-vanmeer** 2023-11-06 00:24 UTC
Labels: bug
